### ISSUE TITLE
About the Datasets

### ISSUE THREAD

**Issue by LeeX-Bruce** [levayz/DINOv2-based-Self-Supervised-Learning#1]
Thank for your outstanding work. 

It would be even better if you could provide the processed dataset. Thanks!

**Comment by levayz** [comment]
Hi, thanks for your comment.
The datasets used are the SYNAPSE dataset and part of the CHAOS dataset so i'm not allowed to upload it myself.
I'll include the processing notebook. I'll do it this weekend.

**Comment by LeeX-Bruce** [comment]
OK, looking forward to your notebook release.

Thank you for your reply and have a good day.

**Comment by levayz** [comment]
Hi, added the notebook + plus instructions in the README file
