### ISSUE TITLE
The code can not run

### ISSUE THREAD

**Issue by LeeX-Bruce** [levayz/DINOv2-based-Self-Supervised-Learning#2]
Can you update the code?

**Comment by levayz** [comment]
because of the dataset?

**Comment by LeeX-Bruce** [comment]
The following problem occurred, I checked **main.sh** and found that the `NSTEP` parameter was probably set incorrectly, so I set it to `100100`. The changed code is now running. Not sure if I did this correctly?
![image](https://github.com/levayz/DINOv2-based-Self-Supervised-Learning/assets/56881416/c1dd265b-3ce0-4ccb-a7f9-432894a7c744)
![image](https://github.com/levayz/DINOv2-based-Self-Supervised-Learning/assets/56881416/8b896d37-290a-4c35-b75a-7e694dc06f7d)

**Comment by LeeX-Bruce** [comment]
When I run `. /main.sh validation mri 1`, the program reports the following error, how can I fix it.
![image](https://github.com/levayz/DINOv2-based-Self-Supervised-Learning/assets/56881416/87600103-cd17-48d5-9ae9-549114f38035)


The training phase has been successfully completed and the following files have been obtained.
![image](https://github.com/levayz/DINOv2-based-Self-Supervised-Learning/assets/56881416/163d6362-b463-43ae-afdd-c9a53112879b)

**Comment by levayz** [comment]
Hi thanks for letting me know, I'll take a look at it, but i think what happens is that the alpmodule fails to find a prototype. This happens sometimes if during training the random superpixel is small. I'll add a try and except if that happens during training.

**Comment by levayz** [comment]
I suggest that you disable TTT (Test Time training) at first, in the main.sh script). 
And if you decide to use it, reduce N_steps to its previous value or even lower (the method finetunes it self on a single image so no neet for 100k steps).

Also - I think you forgot to load your checkpoint (see main.sh RELOAD_PATH)

**Comment by LeeX-Bruce** [comment]
Thank you for your prompt reply! I disabled TTT and load my checkpoint and got validation results. 

Also I would like to ask, if I want to use TTT for validation, then `N_steps` should be set to a smaller value, whereas for training, `N_steps` set to `100k` steps is fine, is that what you mean?

**Comment by levayz** [comment]
yes exactly. during training set to 100k, during validation with TTT use <100.

**Comment by LeeX-Bruce** [comment]
Thank you for your reply and help!

**Comment by LeeX-Bruce** [comment]
Hi, the following error occurred while I was running the `./main.sh training mri 2`: 
![image](https://github.com/levayz/DINOv2-based-Self-Supervised-Learning/assets/56881416/db6ee2f3-dd6c-4125-926f-4c2103a44ae0)

And here are the configurations I am using: 
![image](https://github.com/levayz/DINOv2-based-Self-Supervised-Learning/assets/56881416/08163c12-c9f3-431d-9c2d-cbdc8eb07a6d)

**Comment by levayz** [comment]
This sometimes happens when the model fails to find prototypes. I added a try-catch during training so it won't happen (it was commented out in the original code)
