### ISSUE TITLE
CHAOST2 dataset

### ISSUE THREAD

**Issue by UreMine02** [levayz/DINOv2-based-Self-Supervised-Learning#3]
I have processed the data like your instructions in the ReadMe file. My processed data contains 1 classmap.json file, 840 nii.gz images, and 840 nii.gz label images. I still can not understand how to divide data into 4 tasks (LK, RK, SPLEEN, LIVER) because when I use the classmap file, the label image has other organs. See your reply soon.

**Comment by levayz** [comment]
For training, this is handled in the SuperpixelDataset in GenericSuperDatasetv2.py.
For testing see the validation script: how test_labels is generated (see also dataset_utils.py)

**Comment by levayz** [comment]
closing
