### ISSUE TITLE
When processing CHAOST2 data, an error occurred.

### ISSUE THREAD

**Issue by APeiZou** [levayz/DINOv2-based-Self-Supervised-Learning#4]
@levayz    When processing CHAOST2 data, an error occurred.  ./data/CHAOST2/dcm_img_to_nii.sh: line 19: ./dcm2niix: No such file or directory

**Comment by levayz** [comment]
Hi, you need to install dcm2niix.
Please see this repo: https://github.com/rordenlab/dcm2niix.git

or do this:

```
git clone https://github.com/rordenlab/dcm2niix.git
cd dcm2niix/console
make
./dcm2niix
