### ISSUE TITLE
Does this model require true labels during the training process? What are the differences between pseudo-labels and true labels? Is it that self-supervised learning does not require labels?

### ISSUE THREAD

**Issue by APeiZou** [levayz/DINOv2-based-Self-Supervised-Learning#5]
@levayz   Hello， Does this model require true labels during the training process? What are the differences between pseudo-labels and true labels? Is it that self-supervised learning does not require labels?

**Comment by levayz** [comment]
Hi,
The model doesn't require true labels for training (they are only used for testing). Pseudo labels are superpixels generated from the training data and they serve as the labels. Please see our paper for further details.
https://arxiv.org/abs/2403.03273
